### ISSUE TITLE
Reagent 0.8 on Node doesn't work with foreign libs

### ISSUE THREAD

**Issue by kommen** [reagent-project/reagent#310]
I'm trying to get server side rendering working with ClojureScript 1.9.908 and reagent 0.8.0 alpha1, and we can't use `:npm-deps` due to incompatibilities between some react components and Closure compiler. (same codebase for browser and nodejs target)

The project compiles fine, but node crashes at runtime with `Error: Cannot find module 'react'`

I'm attaching a minimal test case.

To reproduce: 

1) run `boot dev`
2) run `cd target; node nodereagent`

[nodereagent.zip](https://github.com/reagent-project/reagent/files/1263011/nodereagent.zip)

**Comment by Deraen** [comment]
I downloaded the zip and I'm seeing a different error:

```
❯ cd target; node nodereagent
/home/juho/tmp/nodereagent/target/nodereagent.out/cljsjs/react-dom-server/development/react-dom-server.inc.js:15113
module.exports = ReactInternals.ReactComponentTreeHook;
                               ^

TypeError: Cannot read property 'ReactComponentTreeHook' of undefined
    at Object.122 (/home/juho/tmp/nodereagent/target/nodereagent.out/cljsjs/react-dom-server/development/react-dom-server.inc.js:15113:32)
    at s (/home/juho/tmp/nodereagent/target/nodereagent.out/cljsjs/react-dom-server/development/react-dom-server.inc.js:32:333)
    at /home/juho/tmp/nodereagent/target/nodereagent.out/cljsjs/react-dom-server/development/react-dom-server.inc.js:32:384
    at Object.45.122 (/home/juho/tmp/nodereagent/target/nodereagent.out/cljsjs/react-dom-server/development/react-dom-server.inc.js:7956:30)
    at s (/home/juho/tmp/nodereagent/target/nodereagent.out/cljsjs/react-dom-server/development/react-dom-server.inc.js:32:333)
    at /home/juho/tmp/nodereagent/target/nodereagent.out/cljsjs/react-dom-server/development/react-dom-server.inc.js:32:384
    at Object.59.45 (/home/juho/tmp/nodereagent/target/nodereagent.out/cljsjs/react-dom-server/development/react-dom-server.inc.js:9114:24)
    at s (/home/juho/tmp/nodereagent/target/nodereagent.out/cljsjs/react-dom-server/development/react-dom-server.inc.js:32:333)
    at /home/juho/tmp/nodereagent/target/nodereagent.out/cljsjs/react-dom-server/development/react-dom-server.inc.js:32:384
    at Object.68.148 (/home/juho/tmp/nodereagent/target/nodereagent.out/cljsjs/react-dom-server/development/react-dom-server.inc.js:10019:28)
```

What node version are you using?
Do you have `node_modules` directory present?

**Comment by kommen** [comment]
```$ node --version
v8.4.0
```

No `node_modules` present.

**Comment by TerjeNorderhaug** [comment]
Upgrading the react npm module from 15.6.1 to 16.0.0-beta.5 fixed the "Cannot read property 'ReactComponentTreeHook' of undefined" issue for me.

**Comment by Deraen** [comment]
I think I might have hit this problem when trying to rework Reagent tests:

```
❯ lein with-profile node-test doo node client once                                                  

;; ======================================================================
;; Testing with Node:

Error: Cannot find module 'react'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at webpackUniversalModuleDefinition (/home/juho/Source/reagent/out/cljsjs/create-react-class/development/create-react-class.inc.js:3:28)
    at Object.<anonymous> (/home/juho/Source/reagent/out/cljsjs/create-react-class/development/create-react-class.inc.js:10:3)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
Error encountered performing task 'doo' with profile(s): 'node-test'
Subprocess failed
```

Problem seems to be with React UMD wrappers when running on Node. React.inc.js is loaded by Cljs, but looks like that doesn't register module. Create-react-class is loaded by Cljs and the UMD wrapper will try to use `require` on Node as `module.exports` is available.

**Comment by Deraen** [comment]
I hope this Cljs fix will take care of the rest of Node problems: https://github.com/clojure/clojurescript/commit/53070a2c5392e8bdc00bb81c45034268e1cd81f2 tests should pass with both Node + Node modules and Node + foreign libs (#329) after this.
