### ISSUE TITLE
Instructions for excluding react dependency no longer work

### ISSUE THREAD

**Issue by aiba** [reagent-project/reagent#394]
README says:

> If you want to use your own build of React (or React from a CDN), you have to use :exclusions variant of the dependency, and also provide a file named "cljsjs/react.cljs", containing just (ns cljsjs.react), in your project.

This doesn't seem to work in reagent 0.8.1.

In my situation, I'm saddled with a foreign-lib setup that requires me to load react and react-dom before loading clojurescript's main.js.  So I'd love to be able to depend on reagent in a way excludes all the react deps, and instead uses `js/React` and `js/ReactDOM`, when those exist.

**Comment by aiba** [comment]
I took a stab at creating a new stub for js/React.  The idea is to depend on reagent 0.8.1 with `:exclusions [cljsjs/react]` and then define my own react namespace as:

```
(ns react)

(assert js/React)

(def createElement js/React.createElement)
(def Fragment      js/React.Fragment)
(def Children      js/React.Children)
```

This works fine with `:optimizations :none` (despite a warning about single-segment namespace).  With `:optimizations :advanced`, there are fatal errors:

```
----  Compiler Warning : Please see src/cljs-react-stub/react.cljs  ----
Sep 29, 2018 2:39:09 PM com.google.javascript.jscomp.LoggerErrorManager println
SEVERE: /path/to/main.out/reagent/core.js:5: ERROR - required "react" namespace never provided
goog.require('react');
^^^^^^^^^^^^^^^^^^^^^

Sep 29, 2018 2:39:09 PM com.google.javascript.jscomp.LoggerErrorManager println
SEVERE: /path/to/main.out/reagent/impl/component.js:5: ERROR - required "react" namespace never provided
goog.require('react');
^^^^^^^^^^^^^^^^^^^^^

Sep 29, 2018 2:39:09 PM com.google.javascript.jscomp.LoggerErrorManager println
SEVERE: /path/to/main.out/reagent/impl/template.js:5: ERROR - required "react" namespace never provided
goog.require('react');
^^^^^^^^^^^^^^^^^^^^^

Sep 29, 2018 2:39:09 PM com.google.javascript.jscomp.LoggerErrorManager printSummary
WARNING: 3 error(s), 0 warning(s)
ERROR: JSC_MISSING_PROVIDE_ERROR. required "react" namespace never provided at /path/to/main.out/reagent/core.js line 5 : 0
ERROR: JSC_MISSING_PROVIDE_ERROR. required "react" namespace never provided at /path/to/main.out/reagent/impl/component.js line 5 : 0
ERROR: JSC_MISSING_PROVIDE_ERROR. required "react" namespace never provided at /path/to/main.out/reagent/impl/template.js line 5 : 0
```

I was hoping someone could help me figure out how to get the `:optimizations :advanced` build to work.  Many thanks!

**Comment by Deraen** [comment]
It should not be necessary to exclude Cljsjs packages.

If you use webpack add proper `:provides` and `:global-exports` to your `:foreign-libs` entry and it should override foreign-libs from Cljsjs package.

If you use React & others from external files. Hmm, I'm not sure. Problem with what your tried could be that foreign-lib entries have precedence over Cljs namespaces (I'm not sure if this is true). You could try creating similar JS stub and defining foreign-libs entry for that.

I'll try to test and document these ways at some point but I'm quite busy currently.

**Comment by Deraen** [comment]
```
----  Compiler Warning : Please see src/cljs-react-stub/react.cljs  ----
```

Is your `react` stub ns in correct path? It should be in classpath root (i.e. under `src/`).

**Comment by aiba** [comment]
> Is your react stub ns in correct path? It should be in classpath root (i.e. under src/).

Yes, my directory structure has `src/server`, `src/client`, and `src/cljs-react-stub`.  For clojurescript compiler, `"src/client"` and `"src/cljs-react-stub"` are both in the `:source-paths`, so they should be classpath root.

Thank you for the other pointers! I will pursue those ideas.

**Comment by aiba** [comment]
> It should not be necessary to exclude Cljsjs packages.
> If you use webpack add proper :provides and :global-exports to your :foreign-libs entry and it should override foreign-libs from Cljsjs package.

Thank you, this is totally correct.  The trick for me was to add a `:requires ["react" "react-dom"]` to the foreign lib in question.  Everything working wonderfully now.

Again, thank you!
