### ISSUE TITLE
Reagent 0.9.0-rc reports

### ISSUE THREAD

**Issue by Deraen** [reagent-project/reagent#449]
Before pushing out final 0.9.0 release, I'd like to hear reports if this works in existing projects, or if there are regressions. Particularly I'm afraid about mount order change, related to lifecycle method changes: https://github.com/reagent-project/reagent/commit/35ff5d33dd9dda6ac4103bb1bcb88580bdd12ddd

https://clojars.org/reagent/versions/0.9.0-rc1

**Comment by superstructor** [comment]
I'll test this with all the re-frame example apps and re-frame template this evening. Thanks :+1:

**Comment by superstructor** [comment]
As a [first test](https://github.com/Day8/re-frame/commit/7b0f36ce18a9fbe1ba4e6b7fe2d11fbe6132ae2c) re-frame's [tests pass](https://circleci.com/gh/Day8/re-frame/1512) and the two example apps in the same repo (simple and todomvc) work as expected.

**Comment by PrestanceDesign** [comment]
I tested on this two React Native templates and that works :
* https://github.com/thheller/reagent-expo
* https://github.com/seantempesta/expo-cljs-template


I'll try on Re-natal tomorrow : https://github.com/seantempesta/expo-cljs-template

**Comment by superstructor** [comment]
I have released re-frame `0.11.0-rc1` that depends on reagent `0.9.0-rc1` for those who want to use it for testing re-frame apps.

**Comment by oceangroove** [comment]
Hi, I happen to upgrade from 0.8.1 to 0.9.0-rc1 whilst trying to fix an optimisation bug in my clsls/material-ui app.  The problem is with MuiThemeProvider which causes a failure with :optimizations :advanced. but works with :none and :simple

After the reagent version change the error now occurs in all modes.

After the change of reagent version my tested demo and dev versions now produce the following :

    Uncaught Error: No protocol method IKVReduce.-kv-reduce defined for type object: [object 
   Object]

This is a bug in my code but the behaviour has changed with the new version.

logCapturedError | @ | react-dom.inc.js:19952
-- | -- | --
  | logError | @ | react-dom.inc.js:19988
  | update.callback | @ | react-dom.inc.js:21067
  | callCallback | @ | react-dom.inc.js:13067
  | commitUpdateEffects | @ | react-dom.inc.js:13106
  | commitUpdateQueue | @ | react-dom.inc.js:13097
  | commitLifeCycles | @ | react-dom.inc.js:20236
  | commitLayoutEffects | @ | react-dom.inc.js:22951
  | callCallback | @ | react-dom.inc.js:341
  | invokeGuardedCallbackDev | @ | react-dom.inc.js:391
  | invokeGuardedCallback | @ | react-dom.inc.js:448
  | commitRootImpl | @ | react-dom.inc.js:22723
  | unstable_runWithPriority | @ | react.inc.js:2820
  | runWithPriority$2 | @ | react-dom.inc.js:11443
  | commitRoot | @ | react-dom.inc.js:22552
  | scheduleUpdateOnFiber | @ | react-dom.inc.js:21559
  | scheduleRootUpdate | @ | react-dom.inc.js:24457
  | updateContainerAtExpirationTime | @ | react-dom.inc.js:24485
  | updateContainer | @ | react-dom.inc.js:24574
  | (anonymous) | @ | react-dom.inc.js:25101
  | unbatchedUpdates | @ | react-dom.inc.js:21825
  | legacyRenderSubtreeIntoContainer | @ | react-dom.inc.js:25100
  | render | @ | react-dom.inc.js:25180
  | reagent$dom$render_comp | @ | dom.cljs?rel=1568222663383:19
  | (anonymous) | @ | dom.cljs?rel=1568222663383:43
  | reagent$dom$render | @ | dom.cljs?rel=1568222663383:30
  | (anonymous) | @ | dom.cljs?rel=1568222663383:38
  | reagent$dom$render | @ | dom.cljs?rel=1568222663383:30
  | (anonymous) | @ | core.cljs?rel=1568222663783:77
  | reagent$core$render | @ | core.cljs?rel=1568222663783:68
  | sa_draw$views$main$mount_root | @ | main.cljs?rel=1568222691319:151
  | sa_draw$core$init | @ | core.cljs?rel=1568222691514:42
  | (anonymous) | @ | index.html:21

**Comment by oceangroove** [comment]
@Deraen  Thanks for this, I found my optimisation bug in the end after a lot of trial and error.  I only reported the above because of the change in behaviour.  Thanks again.

**Comment by RomanTsopin** [comment]
I've got sample which works in 0.8.1 but fails in 0.9.0-rc1 with 
`TypeError: Cannot read property 'indexOf' of null`

```
(defn page []
  [:div
   (for [i (range 3)
     [:a {:on-click #(js/console.log i)} (str i)])])
(r/render [page] (js/document.getElementById "app"))
```
Interestingly it works ok if I add key metadata
```
(defn page []
  [:div
   (for [i (range 3)]
     ^{:key i} 
     [:a {:on-click #(js/console.log i)} (str i)])])
```

**Comment by vinurs** [comment]
![image](https://user-images.githubusercontent.com/37489300/65207119-4f92a800-dac3-11e9-807c-741841fb3c16.png)
```
(ns app.core
  (:require [reagent.core :as r :refer [atom]]
            ["react-native" :as RN :refer [AppRegistry]]))

(defn app-root []
  [:> RN/View {:style {:flex-direction "column"
                       :margin 40
                       :align-items "center"
                       :background-color "white"}}
   [:> RN/Text {:style {:font-size 30
                        :font-weight "100"
                        :margin-bottom 20
                        :text-align "center"}}
    "Hi Shadow!"]])

(defn init []
  (.registerComponent AppRegistry
                      "YsjApp"
                      #(r/reactify-component app-root)))

```

**Comment by Deraen** [comment]
@RomanTsopin I think I found fix for that problem: https://github.com/reagent-project/reagent/commit/078976de269463c45e2835a42a160cbb3b8f570d

Not sure what could have caused the problem in 0.9.1.

**Comment by Deraen** [comment]
@vinurs I don't see a problem in your example, but I also can't test this React native code.

But, I do have a React native work project which I have tested with 0.9.0-rc1 and it works.

**Comment by vinurs** [comment]
@Deraen hi, i don't know if it's shadow-cljs error, i submit an issue in shadow-cljs
https://github.com/thheller/shadow-cljs/issues/570

**Comment by knubie** [comment]
Experienced a regression on my re-frame app. Don't have a reproducible build yet, but just wanted to flag it here first. The gist is that a component was not re-rendering when subscription(s) updated.

**Comment by Deraen** [comment]
I've pushed out RC2 which fixes the two known problems in RC1: https://github.com/reagent-project/reagent/blob/master/CHANGELOG.md#090-rc2-2019-10-17

**Comment by davidpham87** [comment]
I don't if this is on me or anything else, but I often get an error in reagent/impl/component.cljs:338 because updater is nil, I don't really understand this mistake, and I did not get it before with 0.8.1. The issue usually appears when I am developping wit hot code reloading.

**Comment by knubie** [comment]
FWIW I'm seeing the same regression I reported above in rc2. Sorry I haven't had time to create a reproducible build yet.

**Comment by lins05** [comment]
I have encountered a problem where `:advanced` GCC doesn't work with `0.9.0-rc2`.

Using the node chrome debugger it seems the problem is here:
https://github.com/reagent-project/reagent/blob/078976de269463c45e2835a42a160cbb3b8f570d/src/reagent/impl/batching.cljs#L39-L42

```
TypeError: $c_34539$jscomp$inline_1008$$.$forceUpdate$ is not a function
    at $reagent$impl$batching$RenderQueue$$.$JSCompiler_prototypeAlias$$.flush_render (myproject/target/main.js:14429:93)
    at $reagent$impl$batching$RenderQueue$$.$JSCompiler_prototypeAlias$$.flush_queues (myproject/target/main.js:14403:8)
    at $reagent$impl$batching$RenderQueue$$.$JSCompiler_prototypeAlias$$.run_queues (myproject/target/main.js:14408:15)
    at Timeout._onTimeout (myproject/target/main.js:14387:34)
    at listOnTimeout (internal/timers.js:535:17)
    at processTimers (internal/timers.js:479:7)
```

With `:pretty-print` and `:pseudo-names`  it shows `forceUpdate` got renamed when compiling the cljs file, but it should not be renamed since it's a js object attribute. 

When I downgrade reagent from 0.9.0-rc2 to 0.8.1 this problem is gone immediately.

**Comment by superstructor** [comment]
@lins05 Are you using shadow-cljs, or the standard (i.e. pretty much everything else) cljs compiler ?

**Comment by lins05** [comment]
@superstructor I'm using shadow-cljs. Anything specific to it could cause the bug?

**Comment by Deraen** [comment]
@lins05 Yes, it doesn't use extern files and instead uses externs inference to keep interop calls working with Closure optimization.

#461 should fix this, I guess I should create another RC though I know there are other problems still.

**Comment by lins05** [comment]
@Deraen I just tested locally using #461 and it works with shadow-cljs + adv mode. Thx!

**Comment by Deraen** [comment]
I've now pushed 0.9.0-rc3 with the type hints added. Still need to investigate #462

**Comment by superstructor** [comment]
I've released re-frame 0.11.0-rc3 with reagent bumped to 0.9.0-rc3. Thanks @Deraen

**Comment by mtruyens** [comment]
I added a showcase for a significant regression between 8.1 and 9.0-RC3 in https://github.com/reagent-project/reagent/issues/462

**Comment by vikeri** [comment]
First, thanks a lot Juho for your awesome work on maintaining reagent! You're a star!

I had an issue with 0.9.0-rc4 and advanced compilation. Externs didn't work for `[cljsjs/react "16.8.6-0"]`. I excluded `cljsjs/react` from reagent. But I'm in React Native so I also have react in `package.json`. Ended up removing `cljsjs/react` from my deps and created a hack in the form of a file `src/react.js`:
```js
goog.provides("react");

react = require("react");
```
Given that my setup is a bit of a Frankenstein I'm not sure there's actually a bug in reagent but if anyone else is using react native and struggles with an error like:
```
xDa.Component can't be found
```
then this could be a (hacky) solution.

Also, it's highly likely that I'm just doing something wrong so please correct me if there are better ways of solving this.

**Comment by Deraen** [comment]
My React-native setup uses Reagent with cljsjs denpendecies excluded. Lein-figwheel, and ClojureScript configured with `:target :nodejs` and `:npm-deps true`, so that ClojureScript compiler will emit Node `require` call when it sees `:require` pointing to a Node module, like React or some RN package.

Shadow-cljs should work similarly, `:target :react-native` should be enough there.

Using Reagent with React-Native is a bit of a mess still, as `reagent.core` still depends on `react-dom`, but I will move all DOM functions to separate ns in future. I might also remove cljsjs dependencies, and just leave it to user to select how to provide React.
